server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.55.119.2:3306/NotificationManagement?useSSL=false
    username: root
    password: badbadbad
  application:
    name: notification-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        username: "nacos"
        password: "nacos"

mybatis:
  configuration:
    map-underscore-to-camel-case: true