server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/activity/**
        - id: point-service
          uri: lb://point-service
          predicates:
            - Path=/point/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
        - id: admin-service
          uri: lb://user-service
          predicates:
            - Path=/admin/**